version: 2.1

jobs:
  test:
    docker:
      - image: python:3.10.12-alpine3.18
    steps:
      - checkout
      - run:
          name: "Install Python packages"
          command: "pip3 install --upgrade pip && pip3 install -r requirements.txt"
      - run:
          name: "Run unit tests"
          command: "pytest"
  lint:
    docker:
      - image: python:3.10.12-alpine3.18
    steps:
      - checkout
      - run:
          name: "Install Python packages"
          command: "pip3 install --upgrade pip && pip3 install -r requirements.txt"
      - run:
          name: "Run pylint"
          command: "pylint"

workflows:
  testing-workflow:
    jobs:
      - test
